# Generated by Django 5.2.1 on 2025-07-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='on_duty',
            field=models.BooleanField(default=False, help_text='Is the rider currently available for delivery?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Shop Owner'), ('rider', 'Delivery Rider')], default='customer', max_length=20),
        ),
    ]
