# Generated by Django 5.2.1 on 2025-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_backup_riders_order_delivery_rider_and_more'),
        ('users', '0002_customuser_on_duty_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinCode',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='delivery_pincodes',
            field=models.ManyToManyField(blank=True, to='shop.pincode'),
        ),
    ]
