# Generated by Django 5.2.1 on 2025-06-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
