services:
  - type: web
    name: localshop
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn localshop.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
