# Generated by Django 5.2.1 on 2025-07-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbankinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_pincodes',
            field=models.ManyToManyField(blank=True, related_name='shops', to='shop.pincode'),
        ),
    ]
