# Generated by Django 5.2.1 on 2025-06-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pincode_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='name',
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='gst_number',
            field=models.CharField(default='TEMP-GST', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='ownership_proofs/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_address',
            field=models.TextField(default='TEMP Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(default='shop_name', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShopBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('preferred_payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI')], default='bank', max_length=50)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
