# Generated by Django 5.2.1 on 2025-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_backup_riders_order_delivery_rider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
