# Generated by Django 5.2.1 on 2025-07-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbankinfo',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unshipped', 'Unshipped'), ('unassigned', 'Unassigned'), ('pending', 'Pending'), ('declined', 'Declined'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
