# Generated by Django 5.2.1 on 2025-07-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopbankinfo_razorpay_account_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbankinfo',
            name='cashfree_beneficiary_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
