# Generated by Django 5.2.1 on 2026-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_delivery_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='area_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
