# Generated by Django 5.2.1 on 2026-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_pincode_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pincode',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
